### ISSUE TITLE
Are you ready?

### ISSUE THREAD

**Issue by paulvi** [brandonborkholder/mirur#11]
There's new JSHint-eclipse http://www.nodeclipse.org/#october2015headlines that I need to include into update site by linking to GitHub pages location. And it will make it slower.

With this however, I am ready to add Mirur as great new feature and inable by default to Enide 2015
http://marketplace.eclipse.org/content/enide-studio-2015-nodejs-javascript-java-and-web-tools

While of cause there will be anoounce on http://www.nodeclipse.org, some users may get it unexpectedly. Is there a nice way to self-discover?

Are you ready to get mirur redistributed and repackaged?

ref Nodeclipse/www.nodeclipse.org#61, #7

**Comment by brandonborkholder** [comment]
Yes, that sounds great.

What do you mean by a nice way to self-discover?

**Comment by paulvi** [comment]
That is when you start using software, not aware of its feature. Then notice something (icon, widget, notification). And that leads to learning of new feature.

I don't remember, does mirur adds Views open by default in Debug perspective?

**Comment by paulvi** [comment]
> I don't remember, does mirur adds Views open by default in Debug perspective?

It does not.

**Comment by brandonborkholder** [comment]
It does not. I didn't think about modifying the debug perspective, but I
think I could  to have them open by default. That would be a good feature
so you don't have to go looking for the views.

I think I'll add that.

**Comment by paulvi** [comment]
Closing this, #17 is for self-disvoery
