### ISSUE TITLE
http://mirur.io/ uses jpg for screenshots

### ISSUE THREAD

**Issue by paulvi** [brandonborkholder/mirur#12]
Just noticed that http://mirur.io/ uses jpg for screenshots

Note, that for such images like screenshot `.png` format usually better as it gives clear, not blurred image, while size usually smaller.

**Comment by brandonborkholder** [comment]
I tested this with my screenshots before uploading them. jpeg compresses these images better than png, though jpeg can sometimes be blurry.  I don't find my screenshots blurry, except for the thumbnail on the video which should be replaced.

**Comment by paulvi** [comment]
closing
