### ISSUE TITLE
http://mirur.io/ Small, self describing picture

### ISSUE THREAD

**Issue by paulvi** [brandonborkholder/mirur#13]
I was looking for Small, self describing picture, like below, but should be small enough to fit within http://www.nodeclipse.org/#news

.. well, I think I will take http://mirur.io/images/mirur-example.jpg, just scale it a bit with HTML tag width

![](http://mirur.io/images/mirur-example.jpg)

half-size

![mirur-example-half](https://cloud.githubusercontent.com/assets/1614482/11015839/c9d08a52-85a8-11e5-8a29-b623f28d99d7.jpg)

**Comment by brandonborkholder** [comment]
Is this a question? It's fine if you want to take that image.

**Comment by paulvi** [comment]
yes, actually self-answered. It was a way to let you know, that files are referenced, don't remove to keep links unbrocken
