### ISSUE TITLE
http://mirur.io/ first problem with #11

### ISSUE THREAD

**Issue by paulvi** [brandonborkholder/mirur#14]
first problem with #11

I am in Shenzhen, China , it is midnight Saturday-Sunday, not that much congested time

![image](https://cloud.githubusercontent.com/assets/1614482/11015911/7ed3b4e0-85ab-11e5-8687-497353033c7f.png)

**Comment by paulvi** [comment]
8MB seems to be too big to be included by default :-(

**Comment by brandonborkholder** [comment]
I'm working on this.

**Comment by brandonborkholder** [comment]
I've fixed this with 1247b1e. Download should be less 3MB total.

**Comment by paulvi** [comment]
That is awesome. When is it going to be released?

**Comment by brandonborkholder** [comment]
It's there now, I just repackaged the latest plugin version with pack200.  It reduced the size from 8MB to 2.5MB.

**Comment by paulvi** [comment]
OK, so it is the same version, just compressed.
