### ISSUE TITLE
Please update marketplace entry for this plugin as "Mirur Visual Debugger (for Java)"

### ISSUE THREAD

**Issue by paulvi** [brandonborkholder/mirur#15]
Please update marketplace entry for this plugin
https://marketplace.eclipse.org/content/mirur

I suggest name as "Mirur Visual Debugger (for Java)"

**Comment by brandonborkholder** [comment]
Mirur Visual Debugger is a good suggestion.

**Comment by paulvi** [comment]
With currently Marketplace https://marketplace.eclipse.org/content/mirur link will still work after renaming

**Comment by brandonborkholder** [comment]
Done

**Comment by paulvi** [comment]
I would add Java into name or free tags, to make it easier for Java Developers to find mirur

**Comment by brandonborkholder** [comment]
I added Java into the tags.
