### ISSUE TITLE
Modify Debug perspective or add new

### ISSUE THREAD

**Issue by paulvi** [brandonborkholder/mirur#17]
started in https://github.com/brandonborkholder/mirur/issues/11#issuecomment-154886825

When views are already in perspective, user can discover the feature.

Usually it is done by creating new perspective, with extentions, but for debug, there should be only one.

**Comment by brandonborkholder** [comment]
I just checked and I'm already doing this in https://github.com/brandonborkholder/mirur/blob/master/mirur-ui/plugin.xml#L27.

If you install Mirur and open the Debug view the Mirur views will automatically be there in the lower right.

**Comment by paulvi** [comment]
OK, that will be in 1.1

**Comment by brandonborkholder** [comment]
Actually, it's already in 1.0.2
