### ISSUE TITLE
JavaScript arrays?

### ISSUE THREAD

**Issue by paulvi** [brandonborkholder/mirur#2]
Can JavaScript be supported arrays?

**Comment by brandonborkholder** [comment]
Please add more information to this issue.  Enumerate the environment where you would like this functionality - Javascript vm, Eclipse plugins, etc.

**Comment by paulvi** [comment]
For some time I was looking for everything helping JavaScript development with Eclipse http://www.nodeclipse.org 

And now mostly [CromeDevTools](https://github.com/Nodeclipse/nodeclipse-1/tree/master/chromedevtools) are used for Node.js debugging, while Nashorn (JavaScript over Java 8) stays silent.

I cannot even estimate time, but just opened ticket to have discussion and for references.

JavaScript is quite different from Java from the point that variable can have numeric or any other value. (Have you tried ever visualize strings, e.g. by drawing their lengths?)

There should be also nice user story showing when and how visualizing would make big change of have we we debugging.

**Comment by brandonborkholder** [comment]
I have plans to extend the visualization to other datastructures, strings, etc.  I think this lines up well with the MIrur roadmap.

I'll have to take some time to see how easy it is to interface with an arbitrary Javascript vm (or just ChromeDevTools).  Maybe the Eclipse SDK makes this easy.

**Comment by brandonborkholder** [comment]
What's the recommended path for integrating with Enide?  I see two plugins that provide some kind of javascript debugging support - org.chromium.debug and org.nodeclipse.debug.  How do the two interact?

**Comment by brandonborkholder** [comment]
I just finished support for javascript arrays in Mirur 1.1.0 (26c55e6d).  I tested it with Enide Studio 2014 and 2015.

**Comment by paulvi** [comment]
This is phenomenal. I will give a try this month.

**Comment by paulvi** [comment]
It works

![image](https://cloud.githubusercontent.com/assets/1614482/12753226/23df8902-ca01-11e5-83ba-a084b1b57b1d.png)
